name: linuxpowertoys
description: Bring Microsoft's PowerToys utilities to Linux world!
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.8.0-preview

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  gsettings:
    git:
      url: https://github.com/canonical/gsettings.dart
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.8
  dbus: ^0.7.8
  shell: ^2.0.0
  logging: ^1.2.0
  package_info_plus: ^8.0.0
  collection: ^1.17.1
  colornames: ^0.1.0
  archive: ^3.6.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_icon_48x48.png
    - assets/images/app_icon_256x256.png
    - assets/images/FancyZones.png
    - assets/images/General.png
